//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OKP1_Stationeers_Editor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OKP1_Stationeers_Editor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;AtmosphereSaveData&gt;
        ///    &lt;Position&gt;
        ///        &lt;x&gt;0&lt;/x&gt;
        ///        &lt;y&gt;0&lt;/y&gt;
        ///        &lt;z&gt;0&lt;/z&gt;
        ///    &lt;/Position&gt;
        ///    &lt;Oxygen&gt;0&lt;/Oxygen&gt;
        ///    &lt;Nitrogen&gt;0&lt;/Nitrogen&gt;
        ///    &lt;CarbonDioxide&gt;0&lt;/CarbonDioxide&gt;
        ///    &lt;Volatiles&gt;0&lt;/Volatiles&gt;
        ///    &lt;Chlorine&gt;0&lt;/Chlorine&gt;
        ///    &lt;Water&gt;0&lt;/Water&gt;
        ///    &lt;NitrousOxide&gt;0&lt;/NitrousOxide&gt;
        ///    &lt;Energy&gt;0&lt;/Energy&gt;
        ///    &lt;Volume&gt;0&lt;/Volume&gt;
        ///    &lt;Direction&gt;
        ///        &lt;x&gt;0&lt;/x&gt;
        ///        &lt;y&gt;0&lt;/y&gt;
        ///        &lt;z&gt;0&lt;/z&gt;
        ///    &lt;/Direction&gt;
        ///    &lt;NetworkReferenceId&gt;0&lt;/NetworkReferenceId&gt;
        ///    &lt;ThingReferenceId&gt;0&lt;/ThingRef [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AtmosphereSaveDataTemplate {
            get {
                return ResourceManager.GetString("AtmosphereSaveDataTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CloseXSmall {
            get {
                object obj = ResourceManager.GetObject("CloseXSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CloseXSmallRed {
            get {
                object obj = ResourceManager.GetObject("CloseXSmallRed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ThingSaveData&gt;
        ///  &lt;ReferenceId /&gt;
        ///  &lt;PrefabName /&gt;
        ///  &lt;CustomName /&gt;
        ///  &lt;WorldPosition&gt;
        ///    &lt;x&gt;0.0&lt;/x&gt;
        ///    &lt;y&gt;0.0&lt;/y&gt;
        ///    &lt;z&gt;0.0&lt;/z&gt;
        ///  &lt;/WorldPosition&gt;
        ///  &lt;WorldRotation&gt;
        ///    &lt;x&gt;0.0&lt;/x&gt;
        ///    &lt;y&gt;0.0&lt;/y&gt;
        ///    &lt;z&gt;0.0&lt;/z&gt;
        ///    &lt;w&gt;0.0&lt;/w&gt;
        ///    &lt;eulerAngles&gt;
        ///      &lt;x&gt;0&lt;/x&gt;
        ///      &lt;y&gt;0&lt;/y&gt;
        ///      &lt;z&gt;0&lt;/z&gt;
        ///    &lt;/eulerAngles&gt;
        ///  &lt;/WorldRotation&gt;
        ///  &lt;States /&gt;
        ///  &lt;IsCustomName&gt;false&lt;/IsCustomName&gt;
        ///  &lt;CustomColorIndex&gt;-1&lt;/CustomColorIndex&gt;
        ///  &lt;OwnerSteamId&gt;0&lt;/OwnerSteamId&gt;
        ///  &lt;Reagents /&gt;
        ///  &lt;Indestructable&gt;false&lt;/Indestructable&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LockerItemTemplate {
            get {
                return ResourceManager.GetString("LockerItemTemplate", resourceCulture);
            }
        }
    }
}
